# Generated by Django 5.2.5 on 2025-08-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_especialidade', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='medico',
            name='email',
            field=models.EmailField(default=100, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='nome_especialidade',
            field=models.ManyToManyField(to='medico.especialidade'),
        ),
    ]
